[package]
name = "service"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "service"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.95"
atom_syndication = "0.12.4"
dto = { path = "../../dto" }
entity = { path = "../entity" }
futures = "0.3.31"
log = "0.4.25"
nanoid = "0.4.0"
readability = { version = "0.2.0", features = ["reqwest"] }
regex = "1.11.1"
reqwest = "0.11.27"
rss = "2.0.11"
sea-orm = { version = "^1.1" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
time = "0.3.37"
tokio = "1.43.0"
urlnorm = "0.1.4"
