[package]
name = "service"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "service"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
sea-orm = { version = "^0" }
serde = { version = "1.0.163", features = ["derive"] }
