[workspace]
members = [
    "entity",
    "frontend",
    "frontend/components",
    "frontend/pages",
    "frontend/stores",
    "server",
    "server/api",
    "server/migration",
    "server/service"
]
