[workspace]
members = [
    "dto",
    "entity",
    "frontend",
    "frontend/components",
    "frontend/pages",
    "frontend/router",
    "frontend/stores",
    "server",
    "server/api",
    "server/migration",
    "server/service"
]

[profile.release]
lto = true
