[package]
name = "stores"
version = "0.1.0"
edition = "2021"

[lib]
name = "stores"
path = "src/lib.rs"

[dependencies]
entity = { path = "../../entity" }
yew = { version = "0.20.0", features = ["csr"] }
yewdux = "0.9.3"
