[package]
name = "pages"
version = "0.1.0"
edition = "2021"

[lib]
name = "pages"
path = "src/lib.rs"

[dependencies]
components = { path = "../components" }
hooks = { path = "../hooks" }
stores = { path = "../stores" }
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
router = { path = "../router" }
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
yewdux = "0.9.3"
