//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::article::Entity as Article;
pub use super::category::Entity as Category;
pub use super::rss_feed::Entity as RssFeed;
pub use super::rss_feed_category::Entity as RssFeedCategory;
