//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rss_feed_category")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub rss_feed_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub category_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::CategoryId",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Category,
    #[sea_orm(
        belongs_to = "super::rss_feed::Entity",
        from = "Column::RssFeedId",
        to = "super::rss_feed::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RssFeed,
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::rss_feed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RssFeed.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
